### ISSUE TITLE
Doesn't seem to be posting to slack

### ISSUE THREAD

**Issue by marks** [agermanidis/TranscriptBot#1]
I see the following in my console but the messages dont seem to be making it into Slack

```
$ transcriptbot record -i 0 -k https://hooks.slack.com/services/XYZ -n MarkMic
--------------------------------------
TranscriptBot v0.1
Audio device............ 0
Name.................... MarkMic
Hook.................... my-new-hook (https://hooks.slack.com/services/XYZ)
No Slack Mode........... False
--------------------------------------
[2016-05-17 08:35:48] Just one
[2016-05-17 08:35:58] Test 1 2 3 4 5
```

The Slack channel did show that an integration was added.

Thanks in advance for your help -- cool stuff!

**Comment by marks** [comment]
... just kidding. I somehow copied the hook wrong. I'll close this and open a different issue suggesting some error checking on the hook URL

**Comment by agermanidis** [comment]
Thanks, adding validation for the hook URL is a good idea.
